Add version function feature

diff --git a/bin/package b/bin/package
--- a/bin/package
+++ b/bin/package
@@ -26,6 +26,10 @@ function noop ()
 {
     true
 };
+function version ()
+{
+    noop
+};
 function installed()
 {
     noop
@@ -52,7 +56,7 @@ function package ()
 };
 function package_cat ()
 {
-    cat "$1" 2> /dev/null || wget -q "$1" -O -
+    wget -q "$1" -O - || cat "$1"
 };
 function package_cache ()
 {
@@ -80,6 +84,10 @@ function package_flatten ()
     };
     function sourced ()
     {
+        test "$#" -ne 0 || {
+          printf $'sourced <<< \'%s\'\n' "$(cat -)"
+          return
+        }
         template "${FUNCNAME[0]}" "$@"
     };
     function executable ()
@@ -87,6 +95,10 @@ function package_flatten ()
         template "${FUNCNAME[0]}" "$@"
     };
     function installed()
+    {
+        template "${FUNCNAME[0]}" "$@"
+    };
+    function sourceable ()
     {
         template "${FUNCNAME[0]}" "$@"
     };
@@ -99,26 +111,36 @@ function package_ls ()
 };
 function package_install ()
 {
+    local bin
     function linked ()
     {
-        ln -s "$2" ".package/$1"
+        ! test -f "$PWD/.package_install/$1" || return 0
+        test "$#" -ne 1 || {
+          bin="$(readlink -f "$(which "$1")")"
+          ln -s "$bin" "$PWD/.package_install/$1"
+          log "linked $bin with alias $1"
+          return
+        }
+        ln -s "$2" "$PWD/.package_install/$1"
         log "linked $2 with alias $1"
     };
     function executable ()
     {
-        local file_path=".package/$1";
+        local file_path=".package_install/$1";
         package_cat "$2" > "$file_path";
         chmod +x "$file_path"
         log "fetched executable $2 with alias $1"
     };
     function sourced ()
     {
-        package_cat "$1" > ".package/$(package_hash "$1")"
+        test "$#" -ne 0 || return 0
+
+        package_cat "$1" > ".package_install/$(package_hash "$1")"
         log "fetched sourced $1"
     };
     function sourceable ()
     {
-        package_cat "$2" > ".package/$1"
+        package_cat "$2" > ".package_install/$1"
         log "fetched sourceable $2 with alias $1"
     };
     function installed ()
@@ -134,19 +156,19 @@ function package_install ()
         rm "$tmp"
         log "installed $1"
     };
-    mv .package .package.bak;
-    mkdir -p ".package";
-    package_flatten "$@" | source /dev/stdin || {
-        log "reverting to previous install"
-        rm -r .package;
-        mv .package.bak .package;
-        log "aborting install"
-        return 1
-    };
-    log "removing old install"
-    rm -r .package.bak;
-    log "install was a success"
-    echo 'source <(package sourced)'
+    [[ -e .package_install ]] && rm -r .package_install # Cleanup
+    {
+        mkdir -p ".package_install";
+        package_flatten "$@" | source /dev/stdin || {
+            log "reverting to previous install"
+            log "aborting install"
+            return 1
+        };
+        log "removing old install"
+        rm -r .package
+        mv .package_install .package
+        log "install was a success"
+    } >&2
 };
 function package_hash ()
 {
@@ -157,15 +179,32 @@ function package_sourced ()
 {
     function sourced ()
     {
+        test "$#" -ne 0 || {
+            cat -;
+            return
+        };
         package_cache "$1"
     };
     mkdir -p ".package";
-    echo "export PATH=\"$PWD/.package:$PATH\"";
+    echo "export PATH=\".package:$PWD/.package:$PATH\"";
     package_flatten "$@" | source /dev/stdin
 };
 function package_file ()
 {
     echo "${1:-./package.sh}"
+};
+function package_run ()
+{
+    export PATH=".package"
+    $@
+}
+function package_version ()
+{
+    version()
+    {
+      echo "$1"
+    };
+    source "$(package_file "$@")"
 }
     function package_help () 
     { 
@@ -182,8 +221,8 @@ function package_file ()
     };
     function package_completion () 
     { 
-        ! type "package_completion_overwrite" &> /dev/null || { 
-            package_completion_overwrite;
+        ! type "_package_completion" &> /dev/null || { 
+            "_package_completion";
             return
         };
         printf 'complete -W "';
@@ -193,6 +232,14 @@ function package_file ()
         done;
         printf '" package;\n'
     };
-    BASHIONISTA_SUBCOMMAND="${1:-main}";
+    test "$#" -ne 0 || { 
+        "_package_default" "$@";
+        exit
+    };
+    BASHIONISTA_SUBCOMMAND="${1:-}";
+    type "package_${BASHIONISTA_SUBCOMMAND:-}" &> /dev/null || { 
+        "_package_fallback" "$@";
+        exit
+    };
     shift || true;
     "package_${BASHIONISTA_SUBCOMMAND:-}" "$@"
